---
abstract: 'Anonymous Plack::Middlewares'
author:
  - 'Paul Driver <frodwith@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101582, CPAN::Meta::Converter version 2.101600'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Inline
requires:
  Plack::Middleware: 0
version: 0.02
